name: Auto Telegram Post

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Send Telegram Message
        run: |
          python3 << 'EOF'
          import os
          import json
          import urllib.request
          import urllib.parse
          import subprocess

          BOT = os.environ['BOT_TOKEN']
          CID = os.environ['CHANNEL_ID']

          subprocess.run(['git','fetch','origin','master'], check=True)
          subprocess.run(['git','checkout','origin/master','--','data/jobs.json'], check=True)

          with open('data/jobs.json', 'r', encoding='utf-8') as f:
              data = json.load(f)

          a = data[-1]
          h = a.get('highlights', {})

          msg = f"🔥 Nayi Khabar - SarthakYojana.in\n\n{a.get('title','')}\n\nVacancy: {h.get('vacancy','-')}\nLast Date: {h.get('applyDate','-')}\n\nhttps://sarthakyojana.in/pages/job-detail.html?id={a.get('id','')}"

          url = f"https://api.telegram.org/bot{BOT}/sendMessage"

          payload = urllib.parse.urlencode({
              "chat_id": CID,
              "text": msg
          }).encode()

          urllib.request.urlopen(url, data=payload)

          print("Message Sent")
          EOF

        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
