name: Auto Telegram Post

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  telegram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Telegram Script
        run: python3 script.py
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
